CREATE TABLE cadastros(
id BIGINT NOT NULL AUTO_INCREMENT,
medico_id BIGINT NOT NULL,
paciente_id BIGINT NOT NULL,
data DATETIME NOT NULL,

PRIMARY KEY(id),
CONSTRAINT FK_IDMEDICO FOREIGN KEY(medico_id) REFERENCES medicos(id),
CONSTRAINT FK_IDPACIENTE FOREIGN KEY(paciente_id) REFERENCES pacientes(id)
)